import type { Metadata } from "next";
//import ErrorWrapper from "./error-wrapper";


export const metadata: Metadata = {
  title: {
    default: "Create Next App",
    template: "%s | Create Next App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
            marginBottom: "1rem"
          }}
        >Header</header>

        {/* Global Exception for handling error */}
        {/* <ErrorWrapper> */}
          {children}
        {/* </ErrorWrapper> */}


        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
            marginTop: "1rem"
          }}
        >Footer</footer>
      </body>
    </html>
  );
}
